# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dylan Fisher
email: hi@dylanfisher.com
description: >
  Dylan Fisher is a full stack Ruby on Rails developer based in New York City.
  He is a partner at <span class='labud-link-wrapper'><a href='http://labud.nyc/'>Labud</a></span> and teaches Core Interaction
  at Parsons School of Design.
baseurl: ""
url: "http://dylanfisher.github.io/"
twitter_username: xverdxse
github_username:  dylanfisher

# Gloabl permalink settings
permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown
sass:
  style: compressed

# Excludes
exclude: ["Guardfile"]

# Custom collections
collections:
  projects:
    output: true

# Defaults
defaults:
  - scope:
      type: projects
    values:
      layout: project
      permalink: /:collection/:title
