# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dylan Fisher
email: hi@dylanfisher.com
description: >
  I'm a web developer and programmer with a background in Fine Arts.
  I work at <a href='http://www.linkedbyair.net/' target='_blank'>Linked by Air</a>
  and enjoy collaborating with others.
baseurl: ""
url: "http://dylanfisher.github.io/"
twitter_username: xverdxse
github_username:  dylanfisher

# Build settings
markdown: kramdown
sass:
    style: compressed

# Excludes
exclude: ["Guardfile"]

# Custom collections
collections:
  projects:
    output: true

# Defaults
defaults:
  - scope:
      type: projects
    values:
      layout: project
      permalink: /:collection/:title
