# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dylan Fisher
email: hi@dylanfisher.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a web developer and programmer with a background in Fine Arts.
  I work at <a href='http://www.linkedbyair.net/' target='_blank'>Linked by Air</a>
  and enjoy collaborating with others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dylanfisher.github.io/" # the base hostname & protocol for your site
twitter_username: xverdxse
github_username:  dylanfisher

# Build settings
markdown: kramdown
